name: Run hello.sh script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run Docker container
        run: |
          docker build -t firstgit-script .
          docker run --rm firstgit-script

