name: Security scan with Trivy

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image for scan
        run: docker build -f Dockerfile.scan -t cyber-scan .

      - name: Run security scan
        run: docker run --rm cyber-scan
